baseURL = "https://PDHiep0504.github.io/blog/"
languageCode = "vi-VN"
title = "HiT Blog"
theme = "minimalist"

[params]
  author = "Phạm Đình Hiệp"
  description = "Blog chia sẻ kiến thức về Java và JavaScript"
  subtitle = "Chia sẻ kiến thức lập trình mạng"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "certificates"
    name = "Certificates"
    url = "/certificates/"
    weight = 4
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
